### ISSUE TITLE
Please check the contents of the error.

### ISSUE THREAD

**Issue by ponyminnie** [kijai/ComfyUI-Marigold#25]
I'm working on using Anaconda Python 3.11.7 on Windows PowerShell, but it's not downloading properly due to the error below..
(It's my first time working on this, so I'd appreciate it if you could teach me well due to my lack of knowledge.)

>>> from diffusers import DiffusionPipeline
>>> pipeline = DiffusionPipeline.from_pretrained("prs-eth/marigold-v1-0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 671, in from_pretrained
    cached_folder = cls.download(
                    ^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1317, in download
    pipeline_class = _get_pipeline_class(
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\diffusers\pipelines\pipeline_loading_utils.py", line 343, in _get_pipeline_class
    pipeline_cls = getattr(diffusers_module, class_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\diffusers\utils\import_utils.py", line 711, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module diffusers has no attribute MarigoldPipeline

**Comment by kijai** [comment]
Did you post this to right repository? That does not look like my code at all, I'm not loading it directly from hugginface, but first to local files then from there to the pipeline.

**Comment by ponyminnie** [comment]
I tried reinstalling it according to the instructions and it shows up like this in cmd.. :(
 
  File "C:\Users\Administrator\Desktop\ui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
    from diffusers import (
ModuleNotFoundError: No module named 'diffusers'
