### ISSUE TITLE
Install failed  - Cannot import name LCMScheduler from diffuser

### ISSUE THREAD

**Issue by hbardak** [kijai/ComfyUI-Marigold#28]
Hi guys, 

I have an issue after the install preventing me to use the nodes 

```
`Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold\nodes.py", line 5, in <module>
    from .marigold.model.marigold_pipeline import MarigoldPipeline
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
    from diffusers import (
ImportError: cannot import name 'LCMScheduler' from 'diffusers' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.jsonCannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold module for custom nodes: cannot import name 'LCMScheduler' from 'diffusers' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)`
```
Any pointer to get this resolved ? 

thank you !

**Comment by kijai** [comment]
Need to update diffusers version. Common issuse since the Manager wont update it if some other node has lower version requirement. Manual way to do so, for windows portable install, run this in your `ComfyUI_windows_portable` -folder:

`python_embeded\python.exe -m pip install -U diffusers`

**Comment by hbardak** [comment]
awesome thank you ! it worked !
