### ISSUE TITLE
Marigold import failed diffusers after installing new custom nodes

### ISSUE THREAD

**Issue by The-Chilli** [kijai/ComfyUI-Marigold#29]
Adding any other custom node that uses diffusers (pip install diffusers) breaks Marigold and fails to import. 

Current work around seem to be to manually uninstall & reinstall diffusers from python_embeded & main python install (only if also required)

Disabling or uninstalling other nodes added does not fix, only diffusers reinstall will stop the import failed:

comfyui log:
[2024-05-01 13:20] Traceback (most recent call last):
  File "C:\ComfyUi\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUi\ComfyUI\custom_nodes\ComfyUI-Marigold\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUi\ComfyUI\custom_nodes\ComfyUI-Marigold\nodes.py", line 5, in <module>
    from .marigold.model.marigold_pipeline import MarigoldPipeline
  File "C:\ComfyUi\ComfyUI\custom_nodes\ComfyUI-Marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
    from diffusers import (
ImportError: cannot import name 'LCMScheduler' from 'diffusers' (C:\ComfyUi\python_embeded\lib\site-packages\diffusers\__init__.py)

After reinstall, marigold will load normally with no import failed

**Comment by kijai** [comment]
This would only happen if some other node forces **older** specific version of diffusers than `diffusers>=0.25.0` . 

For the same reason I don't want to force a specific version as it has potential to break other stuff using diffusers. The main issue here is that the Manager only checks for the minimum version specified globally across all node requirements, so if there's a node that has lower requirement than I have specified, it will be used and mine ignored.

**Comment by UnirionGames** [comment]
> Adding any other custom node that uses diffusers (pip install diffusers) breaks Marigold and fails to import.
> 
> Current work around seem to be to manually uninstall & reinstall diffusers from python_embeded & main python install (only if also required)
> 
> Disabling or uninstalling other nodes added does not fix, only diffusers reinstall will stop the import failed:
> 
> comfyui log: [2024-05-01 13:20] Traceback (most recent call last): File "C:\ComfyUi\ComfyUI\nodes.py", line 1864, in load_custom_node module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "C:\ComfyUi\ComfyUI\custom_nodes\ComfyUI-Marigold__init__.py", line 1, in from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "C:\ComfyUi\ComfyUI\custom_nodes\ComfyUI-Marigold\nodes.py", line 5, in from .marigold.model.marigold_pipeline import MarigoldPipeline File "C:\ComfyUi\ComfyUI\custom_nodes\ComfyUI-Marigold\marigold\model\marigold_pipeline.py", line 9, in from diffusers import ( ImportError: cannot import name 'LCMScheduler' from 'diffusers' (C:\ComfyUi\python_embeded\lib\site-packages\diffusers__init__.py)
> 
> After reinstall, marigold will load normally with no import failed

same here

**Comment by alenknight** [comment]
I'm having same issue.  how do we update diffusers?

**Comment by alenknight** [comment]
worked.  updated manually the diffusers.  obviously this could break other stuff.
see this issue - @kijai  helped resolve prior = https://github.com/kijai/ComfyUI-Marigold/issues/28
def. worked... but just be aware OTHER stuff could now break.  though if everything updated... SHOULD be ok.

**Comment by shangshangdyx** [comment]
When using: "MarigoldDepthEstimationVideo" node, an error occurred: Error occurred when executing MarigoldDepthEstimationVideo:
name 'MarigoldDepthPipeline' is not defined
When using: "MarigoldDepthEstimation_v2" &"MarigoldDepthEstimation_v2" node ,Error occurred when executing MarigoldModelLoader:
diffusers==0.28 is required for v2 nodes

i use "python -m pip install --upgrade diffusers '' in VENV,and have tried "python -m pip install diffusers==0.28"
but still not work.
only "MarigoldDepthEstimation“node working.
<img width="860" alt="微信图片_20240611115925" src="https://github.com/kijai/ComfyUI-Marigold/assets/25240937/e0367ef9-fbaa-4cd6-b853-c97ec172ab0a">
<img width="853" alt="微信图片_20240611115931" src="https://github.com/kijai/ComfyUI-Marigold/assets/25240937/ff3e8814-8fae-49a1-ab61-e213d4133bf2">

**Comment by shangshangdyx** [comment]
> When using: "MarigoldDepthEstimationVideo" node, an error occurred: Error occurred when executing MarigoldDepthEstimationVideo:使用“MarigoldDepthEstimationVideo”节点时，发生错误：执行MarigoldDepthEstimationVideo时出错： name 'MarigoldDepthPipeline' is not defined未定义名称“MarigoldDepthPipeline” When using: "MarigoldDepthEstimation_v2" &"MarigoldDepthEstimation_v2" node ,Error occurred when executing MarigoldModelLoader:使用“MarigoldDepthEstimation_v2”&“MarigoldDepthEstimation_v2”节点时，执行MarigoldModelLoader时发生错误： diffusers==0.28 is required for v2 nodesV2 节点需要 diffusers==0.28
> 
> i use "python -m pip install --upgrade diffusers '' in VENV,and have tried "python -m pip install diffusers==0.28"我在 VENV 中使用“python -m pip install --upgrade diffusers '”，并尝试过“python -m pip install diffusers==0.28” but still not work.但仍然不起作用。 only "MarigoldDepthEstimation“node working.只有“MarigoldDepthEstimation”节点工作。 <img alt="微信图片_20240611115925" width="860" src="https://private-user-images.githubusercontent.com/25240937/338429618-e0367ef9-fbaa-4cd6-b853-c97ec172ab0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzk0MzAsIm5iZiI6MTcxODA3OTEzMCwicGF0aCI6Ii8yNTI0MDkzNy8zMzg0Mjk2MTgtZTAzNjdlZjktZmJhYS00Y2Q2LWI4NTMtYzk3ZWMxNzJhYjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA0MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NzYwODM4OTllZWUwNjg3YmRmYzkwYWZhYzI1YTZjMmZiZGEzMGNkM2M4NTQ3ZDJjYjIyZDMzYjk0ZWE0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mnJEDPKF_LMpJR3nZysa1p84hncvGRYBPFb3r0DNtOI"> <img alt="微信图片_20240611115931" width="853" src="https://private-user-images.githubusercontent.com/25240937/338429630-ff3e8814-8fae-49a1-ab61-e213d4133bf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzk0MzAsIm5iZiI6MTcxODA3OTEzMCwicGF0aCI6Ii8yNTI0MDkzNy8zMzg0Mjk2MzAtZmYzZTg4MTQtOGZhZS00OWExLWFiNjEtZTIxM2Q0MTMzYmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA0MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOGViNjU3MWVkYWI0NWI2ZWIyMzEwMDYzZDE5YmJkOWVlODMxZjMxN2UwNTdhZjZiMDMyNmE4MzQ2Y2RmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1coOe0P4sgmjG8T4snHgz4FD2m-mP0LQWvQsgvQqnl4">

i upgrade diffusers in my main python,V2 nodes working!!!but  "MarigoldDepthEstimationVideo" nodes still 'MarigoldDepthPipeline' is not defined
