### ISSUE TITLE
After install, no idea how to use?

### ISSUE THREAD

**Issue by enzyme69** [kijai/ComfyUI-Marigold#3]
Would be nice to have workflow screenshot example or json? I cannot produce the depth by guessing.

**Comment by kijai** [comment]
Sure it would, just haven't gotten around that yet. 
As for the passive aggressive remark: you could "guess" by just searching for a "marigold" node.
I don't fully understand all the parameters or how to actually utilize this in workflows yet myself.

**Comment by enzyme69** [comment]
Okey, I cannot find "marigold" because error on macOS install (via PINOKIO)

```
/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/env/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/env/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <0B637046-A38B-3A5C-80C6-E847C27DCCD5> /Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/env/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <874DC6A5-D0DF-3689-AC6F-4836FE4952AC> /Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/env/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")
### Loading: ComfyUI-Manager (V1.7.2)
### ComfyUI Revision: 1793 [cdff0810] | Released on '2023-12-07'
Traceback (most recent call last):
  File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/custom_nodes/ComfyUI-Marigold/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py", line 4, in <module>
    from .marigold.model.marigold_pipeline import MarigoldPipeline
  File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/custom_nodes/ComfyUI-Marigold/marigold/model/marigold_pipeline.py", line 9, in <module>
    from diffusers import (
ModuleNotFoundError: No module named 'diffusers'

Cannot import /Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/custom_nodes/ComfyUI-Marigold module for custom nodes: No module named 'diffusers'
```

**Comment by kijai** [comment]
Seems it's not installing the requirements, I don't know how Pinokio does it, comfyUI manager should do it automatically, manual way would be `pip install -r requirements.txt`

**Comment by Kwisss** [comment]
where to put the files in the tar file? both locations don't work?

**Comment by kijai** [comment]
example: 
![image](https://github.com/kijai/ComfyUI-Marigold/assets/40791699/e9b7543b-63cf-452f-ac5b-0d99204f6d9c)

**Comment by enzyme69** [comment]
@kijai I open the PINOKIO install directory, source env activate bin and then install requirements and place the model, and it seems to work now! Thanks

**Comment by h3llolovely** [comment]
I'm getting a similar error where Marigold node fails to load. I've tried both ComfyUI Manager install as well as manual install to custom_nodes directory. Also Pinokio here.

`Prestartup times for custom nodes:
   0.0 seconds: D:\__AI_Apps\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Marigold
   0.1 seconds: D:\__AI_Apps\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Manager 

Total VRAM 24576 MB, total RAM 65230 MB
xformers version: 0.0.23.post1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
### Loading: ComfyUI-Manager (V2.7)
### ComfyUI Revision: 1945 [c5a369a3] | Released on '2024-01-31'
Traceback (most recent call last):
  File "D:\__AI_Apps\pinokio\api\comfyui.git\app\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\__AI_Apps\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Marigold\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\__AI_Apps\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Marigold\nodes.py", line 5, in <module>
    from .marigold.model.marigold_pipeline import MarigoldPipeline
  File "D:\__AI_Apps\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Marigold\marigold\model\marigold_pipeline.py", line 9, in <module>     
    from diffusers import (
ImportError: cannot import name 'DEISMultistepScheduler' from 'diffusers' (D:\__AI_Apps\pinokio\api\comfyui.git\app\env\lib\site-packages\dif
fusers\__init__.py)

Cannot import D:\__AI_Apps\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Marigold module for custom nodes: cannot import name 'DEISMultist
epScheduler' from 'diffusers' (D:\__AI_Apps\pinokio\api\comfyui.git\app\env\lib\site-packages\diffusers\__init__.py)
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

Import times for custom nodes:
   0.5 seconds: D:\__AI_Apps\pinokio\api\comfyui.git\app\custom_nodes\ComfyWarp
   0.5 seconds: D:\__AI_Apps\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Manager
   0.8 seconds (IMPORT FAILED): D:\__AI_Apps\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Marigold`
