### ISSUE TITLE
Cannot run the nodes

### ISSUE THREAD

**Issue by Reledia** [kijai/ComfyUI-Marigold#8]
Installing the node from the ComfyUI Manager I get this error when restarting the server:

```
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/Marigold-Checkpoint/__init__.py'

Cannot import /run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/Marigold-Checkpoint module for custom nodes: [Errno 2] No such file or directory: '/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/Marigold-Checkpoint/__init__.py'
Traceback (most recent call last):
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py", line 24, in <module>
    empty_text_embed = torch.load(os.path.join(__file__, '..', "empty_text_embed.pt"), map_location="cpu")
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
NotADirectoryError: [Errno 20] Not a directory: '/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py/../empty_text_embed.pt'

Cannot import /run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold module for custom nodes: [Errno 20] Not a directory: '/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py/../empty_text_embed.pt'
```

From what I understand, this error seems to be caused by a line introduced in commit 1a50170

**Comment by ricardofeynman** [comment]
Thanks for this, been looking forward to testing Marigold. Unfortunately getting the same import error at present.

**Comment by kijai** [comment]
I don't understand... what is "Marigold-Checkpoint" ? I can't reproduce this at my end, even on another PC... I didn't use manager to update though, just git.

**Comment by Reledia** [comment]
> I don't understand... what is "Marigold-Checkpoint" ? I can't reproduce this at my end, even on another PC... I didn't use manager to update though, just git.

My bad, that was a backup of the checkpoint in the wrong place. I removed it and tried to restart:

```
Traceback (most recent call last):
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py", line 24, in <module>
    empty_text_embed = torch.load(os.path.join(__file__, '..', "empty_text_embed.pt"), map_location="cpu")
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/run/media/minerva/SSD/ComfyUI/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
NotADirectoryError: [Errno 20] Not a directory: '/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py/../empty_text_embed.pt'

Cannot import /run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold module for custom nodes: [Errno 20] Not a directory: '/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py/../empty_text_embed.pt'
```

The error doesnt change (if not for the __init__ caused by the backup)

**Comment by ricardofeynman** [comment]
I used the manager to install the custom nodes then did the recommended git clone to the diffusers folder inside the models folder.

> NotADirectoryError: [Errno 20] Not a directory: '/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py/../empty_text_embed.pt'
> 
> Cannot import /run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold module for custom nodes: [Errno 20] Not a directory: '/run/media/minerva/SSD/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py/../empty_text_embed.pt'

@kijai These lines with the abbreviated/../directory path listed in the first post, are the same for me. 

The only thing that caught my eye is that doing a ComfyUI Manager install, the file empty_text_embed.pt is situated under /blah//ComfyUI/custom_nodes/ComfyUI-Marigold/

Could the  'custom_nodes/ComfyUI-Marigold/nodes.py/../empty_text_embed.pt'  instead of  'custom_nodes/ComfyUI-Marigold/empty_text_embed.pt' be part of the issue?

**Comment by kijai** [comment]
You are running this where? Which OS? I only have Windows machines to test with currently and it works even with clean install off the manager for me.

**Comment by Reledia** [comment]
> You are running this where? Which OS? I only have Windows machines to test with currently and it works even with clean install off the manager for me.

EndeavourOS. I think the problem could be fixed using pathlib instead of os.join, I will have to try

**Comment by kijai** [comment]
Pushed a potential fix now, assuming this was a path issue.

**Comment by ricardofeynman** [comment]
Linux Mint xfce. On linux the .. command goes back a directory, not sure it's the same on windows. The /../ in 'custom_nodes/ComfyUI-Marigold/nodes.py/../empty_text_embed.pt' caught my attention. Just a guess though, not sure if this would be a factor.

**Comment by Reledia** [comment]
> Pushed a potential fix now, assuming this was a path issue.

Now it loads, thanks
